### ISSUE TITLE
Issues with auto-grader 

### ISSUE THREAD

**Issue by KorinaAn** [code4policy/2023#2]
I am getting some red "x" on most of the files/directories I have pushed to github (on both cowsay and the universe assignments) and I am not sure what I have done wrong , or what auto-grader is trying to tell me. 
![Screen Shot 2023-01-06 at 10 33 15 AM](https://user-images.githubusercontent.com/121821717/211045438-1f92daba-72a1-4b39-8996-778d3812017a.png)
![Screen Shot 2023-01-06 at 10 33 33 AM](https://user-images.githubusercontent.com/121821717/211045445-6b3675de-fd94-4633-9efd-166f938e2b25.png)
![Screen Shot 2023-01-06 at 10 33 49 AM](https://user-images.githubusercontent.com/121821717/211045447-42d7b035-5395-4723-93d7-959c75c59a24.png)
![Screen Shot 2023-01-06 at 10 34 18 AM](https://user-images.githubusercontent.com/121821717/211045449-a79e0cf5-f012-4ead-8da7-cd959b31ba43.png)

**Comment by pcsong33** [comment]
Hi Korina, your universe repository looks good! If there is a green checkmark, that means that your latest update has passed all of the tests! If there's a red checkmark, that means that there is at least one test that is not passing correctly. For the cowsay assignment, it looks like tasks 6,7, and 8 are not passing, which is why there is still a red checkmark. 

You can check out this link:
https://github.com/code4policy/cowsay-KorinaAn/actions/runs/3853012463/jobs/6565609807

As well as the expected answers txt file in your repo to troubleshoot why specific tests are not passing.

**Comment by KorinaAn** [comment]
In my universe repo it has red for "stars" and "other", which I do not understand. 

In the screenshot of the cowsay assignment, all the tasks have a red x next to them, and I don't know what the mistakes are. Everything apart from task 8 should be running properly.

**Comment by KorinaAn** [comment]
Also in task 6, the prompt asks for the bubbles to wrap every 4 characters, and in the expected answers file the bubbles wrap every 3 characters i think.

**Comment by pcsong33** [comment]
Hi Korina, your universe repo has red for "stars" and "other" because when you hadn't correctly completed all of the tasks when you pushed your changes then. In your most recent update "planets", you correctly finished all the tasks, so the green checkmark means that you finished the assignment.

**Comment by pcsong33** [comment]
Your tasks 5 and 6 have small errors. You need to add spaces between your words in task 5 and you have an extra space at the end of your text in task 6. For both, just exactly copy the text that are in the instructions.
